# theme: jekyll-theme-slate
#title: Kamran's Page
# desciption: Feel free to drop me a message
title: "Kamran Badirov"
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Blog"
    url: "/blog/"
